### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by genialkartik** [genialkartik/Macfolio#14]
Need a well-design and easy to get documentation.

**Comment by ackr-8** [comment]
hey i can help you make a good readme.md

**Comment by genialkartik** [comment]
Yeah sure! @ackr-8. The following repo is welcomed for contribution & PRs.
Happy Coding! 👍🏼

**Comment by ampsteric** [comment]
Please assign this is issue to me. I will get it done by tomorrow.

**Comment by genialkartik** [comment]
Looking forward to getting it done at best! 👍🏼

**Comment by ayushi-1408** [comment]
Hey can I work on this issue?

**Comment by genialkartik** [comment]
find bugs! 
fix it or do let me know (by creating Issue [here](https://github.com/genialkartik/Macfolio/issues))
Or just fix typo (if any)
Help in docs!
