### ISSUE TITLE
Script for concurrently running both react and node server

### ISSUE THREAD

**Issue by Nikhil-dev13** [genialkartik/Macfolio#20]
Currently the project has two development servers front-end react server and the back-end node server, and both need to be started individually and also by being on the respective directories. Since concurrently is already been installed as dev  dependency therefore a single script can be made to run both the development servers with the help of concurrently. 

Similarly the  package installation for react side can also be done without changing the directory with the help of a script on server package.json.

Please let me know If this can be done @genialkartik, I would like to contribute to this repository.

**Comment by genialkartik** [comment]
Thanks, @Nikhil-dev13, to dive down into details of the project.
Well, currently the project is in production-ready state. That means you would only need to run build script in the client (frontend) directly and then just by running 'npm start' the app will go live.
I implemented Package 'concurrently' in dev mode but didn't update the same on GitHub (but may find it in the commit history of the project) in the 'macfolio3.0' branch.

Conclusion: current code in master branch is in production-ready mode (state). will update the code of dev mode in branch 'macfolio3.0'.

**Comment by genialkartik** [comment]
I'll create a new issue and will update Readme.md file with proper guidance and documentation. So that You'll and other also will find it easy to contribute to the project.
I'd be pleased with your contribution. 👍🏼

**Comment by Nikhil-dev13** [comment]
Ok, Thanks for your quick response.
I would love to contribute to this repository.

I am closing this issue.
Thank you once again
